/**
 * 种子数据 - 8 个虚拟烂尾项目
 * 用于首页展示，让评审打开就能看到"墓园"的感觉
 */

export const seedProjects = [
  {
    id: "meal-mate",
    name: "MealMate",
    description: '用 AI 解决"今天吃什么"的食谱推荐工具',
    readme: "# MealMate\n\n基于 OpenAI API 的智能食谱推荐应用。\n\n## 功能\n- 用户偏好问卷\n- 食谱卡片展示\n- AI 推荐引擎\n\n## 技术栈\nReact + Tailwind + Express + OpenAI API\n\n## 当前状态\n前端 3 个页面完成，推荐接口对接但质量差，无数据库层。",
    techStack: "React, Tailwind, Express, OpenAI API",
    abandonReason: "推荐算法质量不达标，直接调用 OpenAI 生成推荐太通用，没有针对性",
    contactInfo: "github.com/mealmate-dev",
    licenseType: "MIT",
    mindset: "give-up",
    status: "reviving",
    scoreClarity: "clear",
    scoreBlockerType: "tech",
    scoreReusability: "high",
    scoreDocLevel: "basic",
    scoreUserValue: "medium",
    aiVision: "用 AI 帮你决定今天吃什么，而不是在冰箱前发呆",
    deathDiagnosis: "死在推荐引擎质量。直接调 OpenAI 生成推荐太通用，缺少用户偏好向量匹配(推测：未做 embedding)",
    completionTier: "half-done",
    completionReason: "前端 3 页面完成，推荐接口对接但质量差，无数据库层",
    reusableAssets: ["偏好问卷交互组件", "食谱卡片组件", "推荐Prompt(含失败教训)", "Express路由层(推测)"],
    revivalDifficulty: "medium",
    revivalReason: "阻塞点明确（推荐架构需重写），有 RAG 成熟方案，但需要引入向量数据库",
    recommendedActions: ["disassemble", "revive"],
    revivalPath: "Day1: 重写推荐引擎为RAG架构+接入向量数据库 / Day2: 用户偏好向量化+食谱向量化 / Day3: 联调前端+部署验证",
    aiEpitaph: "死在登录回调和推荐质量之间，离能用只差一个周末，离好用差一次架构下决心",
  },
  {
    id: "tiny-crm",
    name: "TinyCRM",
    description: "一个本想服务自由职业者的小型 CRM 系统",
    readme: "# TinyCRM\n\n轻量级 CRM，面向自由职业者管理客户关系。\n\n## 已完成\n- 客户列表页\n- 基础表单\n\n## 未完成\n- 权限系统\n- 表单校验\n- 数据导出",
    techStack: "Vue 3, Element Plus, Node.js, SQLite",
    abandonReason: "权限系统太复杂，表单校验逻辑写不下去",
    contactInfo: "github.com/tiny-crm",
    licenseType: "MIT",
    mindset: "seeking-handover",
    status: "claimable",
    scoreClarity: "clear",
    scoreBlockerType: "tech",
    scoreReusability: "medium",
    scoreDocLevel: "basic",
    scoreUserValue: "medium",
    aiVision: "让自由职业者用一个轻量工具管客户，而不是被 Salesforce 们淹没",
    deathDiagnosis: "死在权限系统设计。RBAC 角色模型设计过复杂，表单校验逻辑无法收尾(推测：未做表单校验中间件抽象)",
    completionTier: "half-done",
    completionReason: "客户列表页和基础表单已完成，但权限和校验两大核心模块缺失",
    reusableAssets: ["客户列表页组件", "基础表单组件", "Vue项目结构(推测)", "SQLite数据模型"],
    revivalDifficulty: "medium",
    revivalReason: "阻塞点明确（权限+校验），有 casl 等成熟开源方案，但需要重构表单层",
    recommendedActions: ["disassemble", "revive"],
    revivalPath: "Day1: 用 casl 简化权限模块+重写表单校验中间件 / Day2: 补齐数据导出功能 / Day3: 部署+基础e2e测试",
    aiEpitaph: "一个想替自由职业者管客户的 CRM，自己死在了权限校验的迷宫里",
  },
  {
    id: "pomoflow",
    name: "PomoFlow",
    description: "番茄钟 + 心流追踪的专注力管理工具",
    readme: "# PomoFlow\n\n结合番茄工作法和心流状态追踪的生产力工具。\n\n## 功能规划\n- 番茄计时器\n- 心流状态记录\n- 数据可视化报表\n- 专注音乐播放\n\n## 当前进度\n计时器核心功能完成，数据可视化做了一半。",
    techStack: "React, TypeScript, Chart.js, Vite",
    abandonReason: "数据可视化报表太复杂，Chart.js 配置搞不定，做着做着没动力了",
    contactInfo: "github.com/pomoflow",
    licenseType: "MIT",
    mindset: "memorial",
    status: "buried",
    scoreClarity: "clear",
    scoreBlockerType: "motivation",
    scoreReusability: "high",
    scoreDocLevel: "complete",
    scoreUserValue: "medium",
    aiVision: "把番茄钟从计时器升级为心流追踪器，记录你的专注质量而非只是时长",
    deathDiagnosis: "死在数据可视化。Chart.js 配置过于复杂导致放弃(推测：未尝试 Recharts 等更简方案)",
    completionTier: "near-usable",
    completionReason: "计时器核心完成，心流数据模型已设计，仅报表和音乐模块未完成",
    reusableAssets: ["番茄计时器组件", "心流状态数据模型", "TypeScript类型定义", "Vite构建配置(推测)"],
    revivalDifficulty: "easy",
    revivalReason: "核心功能已完成，仅差可视化报表，换 Recharts 可快速补齐",
    recommendedActions: ["bury", "exhibit"],
    revivalPath: "",
    aiEpitaph: "一个帮你专注的工具，自己却没能专注下去，死在了 Chart.js 的配置文档里",
  },
  {
    id: "devport",
    name: "DevPort",
    description: "开发者个人作品集自动生成器",
    readme: "# DevPort\n\n从 GitHub API 自动拉取项目信息，生成个人作品集页面。\n\n## 技术栈\nNext.js + Tailwind + GitHub API\n\n## 状态\nGitHub API 对接完成，页面模板做了 2 个，部署配置没做。",
    techStack: "Next.js, Tailwind CSS, GitHub API",
    abandonReason: "页面模板太少不好看，又不想自己设计，就放着了",
    contactInfo: "github.com/devport-app",
    licenseType: "MIT",
    mindset: "seeking-handover",
    status: "claimable",
    scoreClarity: "clear",
    scoreBlockerType: "design",
    scoreReusability: "high",
    scoreDocLevel: "complete",
    scoreUserValue: "medium",
    aiVision: "从 GitHub API 自动拉取项目生成作品集，让开发者不用手写简历",
    deathDiagnosis: "死在设计能力。页面模板太少不好看，开发者不想自己设计 UI(推测：未尝试 UI 组件库)",
    completionTier: "near-usable",
    completionReason: "GitHub API 对接完成，2 个页面模板已做，仅缺部署配置和更多模板",
    reusableAssets: ["GitHub API 数据获取层", "Next.js项目结构", "页面模板框架", "API路由(推测)"],
    revivalDifficulty: "easy",
    revivalReason: "API 层完整，只需补 UI 模板和主题系统，用 shadcn/ui 可快速解决",
    recommendedActions: ["disassemble", "revive"],
    revivalPath: "Day1: 引入 shadcn/ui+重做页面模板 / Day2: 添加主题系统+部署配置 / Day3: 模板自定义+上线验证",
    aiEpitaph: "一个帮别人展示作品集的工具，自己的作品集却没做完",
  },
  {
    id: "quizai",
    name: "QuizAI",
    description: "AI 自动生成测验题目的教育工具",
    readme: "# QuizAI\n\n输入知识点，AI 自动生成选择题、填空题和简答题。\n\n## 功能\n- 知识点输入\n- AI 题目生成\n- 题目编辑\n- 导出 PDF\n\n## 进度\nAI 生成部分完成，PDF 导出没做，题目编辑器做了一半。",
    techStack: "Python, FastAPI, OpenAI, Jinja2",
    abandonReason: "PDF 导出库太难用，试了 3 个都不行，放弃了",
    contactInfo: "github.com/quizai",
    licenseType: "Apache-2.0",
    mindset: "give-up",
    status: "salvageable",
    scoreClarity: "vague",
    scoreBlockerType: "tech",
    scoreReusability: "medium",
    scoreDocLevel: "basic",
    scoreUserValue: "low",
    aiVision: "输入知识点，AI 自动生成选择题填空题，老师不用手写出卷",
    deathDiagnosis: "死在 PDF 导出。试了 3 个库都不行(推测：未尝试 Puppeteer headless 方案)",
    completionTier: "half-done",
    completionReason: "AI 生成功能可用，题目编辑器做了一半，PDF 导出完全没做",
    reusableAssets: ["AI题目生成Prompt", "FastAPI后端结构", "Jinja2模板(推测)", "题目数据模型"],
    revivalDifficulty: "hard",
    revivalReason: "PDF 导出是硬阻塞，且有题目编辑器未完成，整体继续成本较高",
    recommendedActions: ["disassemble"],
    revivalPath: "",
    aiEpitaph: "一个会出题的 AI，最后被一道 PDF 导出题难倒了",
  },
  {
    id: "fittrack",
    name: "FitTrack",
    description: "极简健身记录打卡 App",
    readme: "# FitTrack\n\n每日健身打卡 + 数据统计的移动端应用。\n\n## 技术栈\nFlutter + Firebase\n\n## 状态\n打卡页面完成，统计页面做了一半，Firebase 配置有问题。",
    techStack: "Flutter, Firebase, Dart",
    abandonReason: "Firebase 配置一直报错，查了两天没解决，心态崩了",
    contactInfo: "github.com/fittrack",
    licenseType: "MIT",
    mindset: "give-up",
    status: "salvageable",
    scoreClarity: "clear",
    scoreBlockerType: "resource",
    scoreReusability: "low",
    scoreDocLevel: "missing",
    scoreUserValue: "low",
    aiVision: "极简的健身打卡 App，帮你记录每天坚持了什么",
    deathDiagnosis: "死在 Firebase 配置。报错查了两天没解决(推测：可能是 GoogleService-Info.plist 配置问题)",
    completionTier: "skeleton",
    completionReason: "仅打卡页面 UI 完成，统计页面半成品，后端配置有问题",
    reusableAssets: ["Flutter打卡页面UI", "Dart模型类(推测)"],
    revivalDifficulty: "hard",
    revivalReason: "后端配置有未解决问题，完成度极低，建议换 Supabase 重写后端",
    recommendedActions: ["disassemble"],
    revivalPath: "",
    aiEpitaph: "一个记录你坚持健身的 App，自己先在 Firebase 配置上没坚持住",
  },
  {
    id: "moodlog",
    name: "MoodLog",
    description: "情绪日记 + AI 情绪分析",
    readme: "# MoodLog\n\n每天记录情绪，AI 分析情绪趋势和触发因素。\n\n## 功能\n- 情绪记录\n- AI 趋势分析\n- 情绪日历热力图\n\n## 进度\n核心记录功能完成，AI 分析接口对接了但 Prompt 没调好，热力图没做。",
    techStack: "React, Node.js, OpenAI API, MongoDB",
    abandonReason: "AI 情绪分析的 Prompt 调不好，输出结果不稳定，做着做着不知道怎么优化了",
    contactInfo: "github.com/moodlog",
    licenseType: "MIT",
    mindset: "seeking-handover",
    status: "reviving",
    scoreClarity: "clear",
    scoreBlockerType: "product",
    scoreReusability: "high",
    scoreDocLevel: "complete",
    scoreUserValue: "high",
    aiVision: "每天记录情绪，AI 帮你发现情绪规律和触发因素，做自己的心理咨询师",
    deathDiagnosis: "死在 Prompt 工程。情绪分析输出不稳定，未引入 few-shot 和结构化输出(推测：Prompt 太宽泛)",
    completionTier: "almost-there",
    completionReason: "核心记录功能完成，AI 接口已对接，仅 Prompt 调优和热力图未做",
    reusableAssets: ["情绪记录组件", "MongoDB数据模型", "情绪趋势分析接口", "React页面结构"],
    revivalDifficulty: "easy",
    revivalReason: "完成度高，阻塞点仅是 Prompt 优化，引入 few-shot 即可解决",
    recommendedActions: ["disassemble", "revive"],
    revivalPath: "Day1: 重写情绪分析Prompt+引入few-shot示例 / Day2: 用 cal-heatmap 实现热力图 / Day3: 联调+部署",
    aiEpitaph: "一个分析你情绪的工具，最后自己情绪崩在了 Prompt 调参上",
  },
  {
    id: "snippetbox",
    name: "SnippetBox",
    description: "代码片段管理 + AI 标签分类工具",
    readme: "# SnippetBox\n\n保存代码片段，AI 自动打标签和分类，支持全文搜索。\n\n## 技术栈\nElectron + React + SQLite\n\n## 状态\n基础保存和列表功能完成，AI 标签分类对接了但分类不准，搜索功能没做完。",
    techStack: "Electron, React, SQLite, OpenAI API",
    abandonReason: "AI 标签分类效果不好，搜索功能也卡住了，而且 Electron 打包遇到了问题",
    contactInfo: "github.com/snippetbox",
    licenseType: "GPL-3.0",
    mindset: "give-up",
    status: "salvageable",
    scoreClarity: "vague",
    scoreBlockerType: "tech",
    scoreReusability: "medium",
    scoreDocLevel: "basic",
    scoreUserValue: "medium",
    aiVision: "保存代码片段，AI 自动打标签分类，再也不用在文件夹里翻找",
    deathDiagnosis: "死在多处：AI 标签分类不准+搜索功能卡住+Electron 打包问题(推测：未尝试 electron-builder)",
    completionTier: "half-done",
    completionReason: "保存和列表功能完成，AI 标签和搜索未完成，打包有阻塞性问题",
    reusableAssets: ["代码片段保存功能", "SQLite数据层", "React列表组件", "OpenAI标签Prompt(含失败教训)"],
    revivalDifficulty: "medium",
    revivalReason: "有 3 个独立阻塞点，但单个都不难解，适合拆件后分别处理",
    recommendedActions: ["disassemble", "exhibit"],
    revivalPath: "",
    aiEpitaph: "一个帮你整理代码的工具，自己的代码却卡在了三个角落里",
  },
];
